# Generated by Django 3.2.3 on 2021-07-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogwrite',
            name='short_description',
            field=models.TextField(default=None),
        ),
    ]
